import { ResearchSession } from "../types";

export class ReportGenerator {
  generateMarkdown(session: ResearchSession): string {
    const { niche, analysis, recommendation, channels } = session;
    const lines: string[] = [];

    lines.push(`# Niche Validation Report: ${niche}`);
    lines.push(`**Session ID:** ${session.id}`);
    lines.push(`**Date:** ${session.createdAt}`);
    lines.push(`**Status:** ${session.status}`);
    lines.push("");

    lines.push("## Overview");
    lines.push(`- **Niche:** ${niche}`);
    lines.push(`- **Keywords:** ${session.keywords.join(", ")}`);
    lines.push(`- **Channels analyzed:** ${channels.length}`);
    lines.push("");

    if (analysis) {
      lines.push("## Niche Analysis");
      lines.push(`- **Saturation:** ${analysis.saturation} (score: ${analysis.saturationScore}/100)`);
      lines.push(`- **Trend:** ${analysis.trendDirection}`);
      lines.push(`- **Avg subscribers:** ${formatNumber(analysis.avgSubscribers)}`);
      lines.push(`- **Avg views:** ${formatNumber(analysis.avgViews)}`);
      lines.push(`- **Avg upload frequency:** ${Math.round(analysis.avgUploadFrequency)} videos`);
      lines.push(`- **Top formats:** ${analysis.topFormats.join(", ")}`);
      if (analysis.relatedNiches.length > 0) {
        lines.push(`- **Related niches:** ${analysis.relatedNiches.join(", ")}`);
      }
      lines.push("");
    }

    if (recommendation) {
      lines.push("## Recommendation");
      lines.push(`### ${recommendation.verdict.toUpperCase()} (confidence: ${recommendation.confidence}%)`);
      lines.push("");
      lines.push(recommendation.summary);
      lines.push("");

      if (recommendation.strengths.length > 0) {
        lines.push("**Strengths:**");
        recommendation.strengths.forEach((s) => lines.push(`- ${s}`));
        lines.push("");
      }
      if (recommendation.risks.length > 0) {
        lines.push("**Risks:**");
        recommendation.risks.forEach((r) => lines.push(`- ${r}`));
        lines.push("");
      }
    }

    if (channels.length > 0) {
      lines.push("## Top Channels");
      lines.push("| Channel | Subscribers | Views | Videos |");
      lines.push("|---------|------------|-------|--------|");
      const top = [...channels]
        .sort((a, b) => b.subscriberCount - a.subscriberCount)
        .slice(0, 10);
      for (const ch of top) {
        lines.push(
          `| ${ch.title} | ${formatNumber(ch.subscriberCount)} | ${formatNumber(ch.viewCount)} | ${ch.videoCount} |`
        );
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by YT_Channel_Stats*");

    return lines.join("\n");
  }
}

function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}
