import { ResearchSession } from "../types";
import { TopicDiscovery } from "../analysis/topic-discovery";

export class ReportGenerator {
  private topics = new TopicDiscovery();

  generateMarkdown(session: ResearchSession): string {
    const { niche, analysis, recommendation, channels } = session;
    const lines: string[] = [];

    lines.push(`# Niche Validation Report: ${niche}`);
    lines.push(`**Session ID:** ${session.id}`);
    lines.push(`**Date:** ${session.createdAt}`);
    lines.push(`**Status:** ${session.status}`);
    lines.push("");

    lines.push("## Overview");
    lines.push(`- **Niche:** ${niche}`);
    lines.push(`- **Keywords:** ${session.keywords.join(", ")}`);
    lines.push(`- **Channels analyzed:** ${channels.length}`);
    lines.push("");

    if (analysis) {
      lines.push("## Niche Analysis");
      lines.push(`- **Saturation:** ${analysis.saturation} (score: ${analysis.saturationScore}/100)`);
      lines.push(`- **Trend:** ${analysis.trendDirection}`);
      lines.push(`- **Avg subscribers:** ${formatNumber(analysis.avgSubscribers)}`);
      lines.push(`- **Avg views:** ${formatNumber(analysis.avgViews)}`);
      lines.push(`- **Avg total videos:** ${Math.round(analysis.avgUploadFrequency)}`);
      lines.push(`- **Upload cadence:** ${analysis.uploadsPerWeek} videos/week`);
      lines.push(`- **Top formats:** ${analysis.topFormats.join(", ")}`);
      lines.push(`- **Engagement rate:** ${analysis.engagementRate}%`);
      lines.push(`- **Avg likes/video:** ${formatNumber(analysis.avgLikesPerVideo)}`);
      lines.push(`- **Avg comments/video:** ${formatNumber(analysis.avgCommentsPerVideo)}`);
      if (analysis.relatedNiches.length > 0) {
        lines.push(`- **Related niches:** ${analysis.relatedNiches.join(", ")}`);
      }
      lines.push("");
    }

    if (recommendation) {
      lines.push("## Recommendation");
      lines.push(`### ${recommendation.verdict.toUpperCase()} (confidence: ${recommendation.confidence}%)`);
      lines.push("");
      lines.push(recommendation.summary);
      lines.push("");

      if (recommendation.strengths.length > 0) {
        lines.push("**Strengths:**");
        recommendation.strengths.forEach((s) => lines.push(`- ${s}`));
        lines.push("");
      }
      if (recommendation.risks.length > 0) {
        lines.push("**Risks:**");
        recommendation.risks.forEach((r) => lines.push(`- ${r}`));
        lines.push("");
      }
    }

    if (channels.length > 0) {
      lines.push("## Top Channels");
      lines.push("| Channel | Subscribers | Views | Videos |");
      lines.push("|---------|------------|-------|--------|");
      const top = [...channels]
        .sort((a, b) => b.subscriberCount - a.subscriberCount)
        .slice(0, 10);
      for (const ch of top) {
        lines.push(
          `| ${ch.title} | ${formatNumber(ch.subscriberCount)} | ${formatNumber(ch.viewCount)} | ${ch.videoCount} |`
        );
      }
      lines.push("");
    }

    // Chrome extraction data
    if (session.chromeData) {
      const cd = session.chromeData;
      if (cd.socialBlade.length > 0) {
        lines.push("## Social Blade Data");
        for (const sb of cd.socialBlade) {
          lines.push(`### ${sb.channelId}`);
          for (const [key, val] of Object.entries(sb)) {
            if (key === "channelId" || key === "status") continue;
            if (val !== null && val !== undefined) {
              lines.push(`- **${key}:** ${val}`);
            }
          }
        }
        lines.push("");
      }

      if (cd.channelPages.length > 0) {
        lines.push("## Channel Page Insights");
        for (const cp of cd.channelPages) {
          const features: string[] = [];
          if (cp.hasMemberships) features.push("Memberships");
          if (cp.hasMerchShelf) features.push("Merch Shelf");
          if (features.length > 0 || cp.linkCount) {
            lines.push(`- **${cp.channelId}:** ${features.join(", ") || "No monetization features detected"} | ${cp.linkCount ?? 0} external links`);
          }
        }
        lines.push("");
      }
    }

    // Topic suggestions
    const topicSuggestions = this.topics.discover(session, 10);
    if (topicSuggestions.length > 0) {
      lines.push("## Topic Opportunities");
      for (const t of topicSuggestions) {
        lines.push(`### ${t.topic} (score: ${t.score}, ${t.source})`);
        lines.push(t.evidence);
        if (t.topVideos && t.topVideos.length > 0) {
          lines.push("");
          lines.push("**Top videos:**");
          for (const v of t.topVideos) {
            lines.push(`- [${v.title}](https://youtube.com/watch?v=${v.videoId}) — ${formatNumber(v.viewCount)} views`);
          }
        }
        lines.push("");
      }
    }

    // Error info
    if (session.error) {
      lines.push("## Errors");
      lines.push(`> ${session.error}`);
      lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by YT_Channel_Stats*");

    return lines.join("\n");
  }
}

function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}
